print("please enter your name")
input()
print("please enter your age")
age = input()
print("print the number of copies needed")
copies = input()
x=(2019+(100-int(age)))
str(x)
print("x\n"*int(copies))
